FROM public.ecr.aws/docker/library/node:22
WORKDIR /test-app

COPY . .

RUN npm install --include=dev --legacy-peer-deps --no-package-lock

RUN npm run build

RUN npx playwright install --with-deps

EXPOSE 3000
CMD ["npm", "run", "dev:backend"]
