#!/usr/bin/env bash
# Format third_party/duckdb C/C++ files with clang-format 11.0.1 (the version
# duckdb's own scripts/format.py enforces) inside a docker container, so no
# local clang-format-11 install is required.
#
# Usage:
#   scripts/format_duckdb.sh                # format files changed vs origin/main
#   scripts/format_duckdb.sh --base <ref>   # format files changed vs <ref>
#   scripts/format_duckdb.sh --files f1 f2  # format an explicit list (paths
#                                             relative to third_party/duckdb)
#   scripts/format_duckdb.sh --check        # report diffs only, do not write
#
# Scoping rules (mirrors third_party/duckdb/scripts/format.py):
#   - only files under: src/ benchmark/ test/ tools/ examples/ extension/ scripts/
#     (third_party/, data/, etc. are skipped -- never reformat vendored code)
#   - skips files/dirs in duckdb's ignored_files / ignored_directories list
#   - skips auto-generated files (those with the
#     "// This file is automatically generated by scripts/" header marker)
#   - only .cpp .hpp .h .c .cc .hh .ipp

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
DUCKDB_DIR="$REPO_ROOT/third_party/duckdb"
IMAGE="python:3.11-slim"

if [[ ! -d "$DUCKDB_DIR/.git" && ! -f "$DUCKDB_DIR/.git" ]]; then
	echo "error: $DUCKDB_DIR is not a git checkout" >&2
	exit 1
fi

BASE_REF="origin/main"
CHECK_ONLY=0
EXPLICIT_FILES=()

while [[ $# -gt 0 ]]; do
	case "$1" in
	--base)
		BASE_REF="$2"
		shift 2
		;;
	--check)
		CHECK_ONLY=1
		shift
		;;
	--files)
		shift
		while [[ $# -gt 0 && "$1" != --* ]]; do
			EXPLICIT_FILES+=("$1")
			shift
		done
		;;
	-h | --help)
		sed -n '2,20p' "$0"
		exit 0
		;;
	*)
		echo "unknown arg: $1" >&2
		exit 2
		;;
	esac
done

FILES_TO_FORMAT="$(mktemp)"
trap 'rm -f "$FILES_TO_FORMAT"' EXIT

# --- collect candidate files ------------------------------------------------
if [[ ${#EXPLICIT_FILES[@]} -gt 0 ]]; then
	printf '%s\n' "${EXPLICIT_FILES[@]}" >"$FILES_TO_FORMAT.raw"
else
	git -C "$DUCKDB_DIR" diff --name-only "${BASE_REF}...HEAD" >"$FILES_TO_FORMAT.raw"
fi

# --- filter: extension, formatted_directories, ignored_files ---------------
ALLOWED_DIRS_RE='^(src|benchmark|test|tools|examples|extension|scripts)/'
EXT_RE='\.(cpp|hpp|h|c|cc|hh|ipp)$'

# duckdb's ignored_files (from scripts/format.py)
IGNORED_FILES_RE='(^|/)(tpch_constants|tpcds_constants|test_csv_header|duckdb|json|sqlite3|shell|termcolor|httplib|os_win|glob|printf|helper|single_thread_ptr|types|default_views|default_functions|release|genrand|address|visualizer_constants|icu-collate|yyjson|duckdb_pdqsort|pdqsort|stubdata|nf_calendar|nf_localedata|nf_zformat|expr|function_list|inlined_grammar)\.(cpp|hpp|h|c|cc|hh|ipp)$'

# duckdb's ignored_directories
IGNORED_DIRS_RE='(/_generated/|^_generated/|tools/rpkg/src/duckdb/|tools/rpkg/inst/include/cpp11/|extension/tpcds/dsdgen/|extension/jemalloc/jemalloc/|extension/icu/third_party/|tools/nodejs/src/duckdb/|/\.eggs/|/__pycache__/|/dbgen/)'

# Team-local exclusions: files whose branch-side edits don't round-trip cleanly
# through clang-format-11 and that we don't want auto-reformatted on every run.
# Format with full-path-prefix matching, anchored at the duckdb-root.
LOCAL_IGNORED_PATHS_RE='^(src/catalog/default/default_types\.cpp)$'

grep -E "$EXT_RE" "$FILES_TO_FORMAT.raw" 2>/dev/null |
	grep -E "$ALLOWED_DIRS_RE" |
	grep -vE "$IGNORED_FILES_RE" |
	grep -vE "$IGNORED_DIRS_RE" |
	grep -vE "$LOCAL_IGNORED_PATHS_RE" \
		>"$FILES_TO_FORMAT.candidates" || true

# Skip auto-generated files (matches duckdb's format.py file_is_generated check):
# any file whose first 2KB contains "// This file is automatically generated by scripts/".
: >"$FILES_TO_FORMAT"
while IFS= read -r f; do
	full="$DUCKDB_DIR/$f"
	[[ -f "$full" ]] || continue
	if head -c 2048 "$full" | grep -q '// This file is automatically generated by scripts/'; then
		continue
	fi
	printf '%s\n' "$f" >>"$FILES_TO_FORMAT"
done <"$FILES_TO_FORMAT.candidates"

rm -f "$FILES_TO_FORMAT.raw" "$FILES_TO_FORMAT.candidates"

COUNT=$(wc -l <"$FILES_TO_FORMAT" | tr -d ' ')
if [[ "$COUNT" -eq 0 ]]; then
	echo "no files to format (base=$BASE_REF)"
	exit 0
fi
echo "scope: $COUNT file(s)"

# --- inner script that runs inside the container ---------------------------
INNER_SCRIPT="$(mktemp)"
trap 'rm -f "$FILES_TO_FORMAT" "$INNER_SCRIPT"' EXIT

CHECK_FLAG=""
[[ "$CHECK_ONLY" -eq 1 ]] && CHECK_FLAG="--dry-run --Werror"

cat >"$INNER_SCRIPT" <<INNER
#!/bin/sh
set -e
pip install --quiet --root-user-action=ignore --no-warn-script-location clang_format==11.0.1
export PATH="/tmp/.local/bin:\$PATH"
cd /work
echo "clang-format: \$(clang-format --version)"
xargs -a /tmp/files.txt -n 50 -P 4 clang-format -i --style=file --sort-includes=0 $CHECK_FLAG
INNER

# --- run --------------------------------------------------------------------
docker run --rm \
	-u "$(id -u):$(id -g)" \
	-v "$DUCKDB_DIR":/work \
	-v "$FILES_TO_FORMAT":/tmp/files.txt:ro \
	-v "$INNER_SCRIPT":/tmp/run.sh:ro \
	-e HOME=/tmp \
	-e PIP_CACHE_DIR=/tmp/pip-cache \
	"$IMAGE" sh /tmp/run.sh

if [[ "$CHECK_ONLY" -eq 1 ]]; then
	echo "check passed."
else
	MODIFIED=$(git -C "$DUCKDB_DIR" diff --name-only | wc -l | tr -d ' ')
	echo "done. $MODIFIED file(s) modified in $DUCKDB_DIR (review with 'git -C third_party/duckdb diff')"
fi
