name: SereneDB-Build-Manual

run-name: "SereneDB [${{ inputs.PRESET }}]"

on:
  workflow_dispatch:
    inputs:
      PRESET:
        description: 'Build preset'
        type: choice
        required: true
        default: 'build'
        options:
          - asan
          - tsan
          - msan
          - ubsan
          - coverage
          - build
      LOCATION:
        description: 'Where the load is executed'
        type: choice
        required: true
        options:
          - X64
          - arm
          - self-hosted
        default: 'X64'
      EXTRA_ARTIFACTS:
        description: 'Keep these artifacts additionally'
        type: string
        required: false
        default: ''
      BUILD_CONFIG:
        description: 'JSON configuration for builds and job settings'
        type: string
        required: false
        default: '{"BUILD_IMAGE":"serenedb/serenedb-build-ubuntu:latest","DEBUG_PRINT_ENV":"false"}'

permissions:
  statuses: write
  contents: write

jobs:
  call-reusable:
    uses: ./.github/workflows/build-reusable.yml
    with:
      PRESET: ${{ inputs.PRESET }}
      LOCATION: ${{ inputs.LOCATION }}
      EXTRA_ARTIFACTS: ${{ inputs.EXTRA_ARTIFACTS }}
      BUILD_CONFIG: ${{ inputs.BUILD_CONFIG }}

    secrets: inherit
